[package]
name = "sagittarius"
version = "0.12.0"
edition = "2021"

[workspace]

[dependencies]
sagittarius-game = { path = "../../game" }
risc0-zkvm = { version = "0.14.0", default-features = false }