[package]
name = "sagittarius-zk"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

risc0-zkvm = { version = "0.14.0", features = ["prove"] }
sagittarius-methods = { path = "../methods" }
sagittarius-game = { path = "../game" }